WCS\LyonGameBundle\Entity\StopOver:
    type: entity
    table: null
    repositoryClass: WCS\LyonGameBundle\Repository\StopOverRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        sequence:
            type: integer
        cost:
            type: integer
        duration:
            type: string
            length: 255
        directive:
            type: text


    manyToMany:
        trips:
            targetEntity: Trip
            mappedBy: stopovers

    manyToOne:
        pointerestStart:
            targetEntity: Pointerest
            inversedBy: stopover
            joinColumn:
                name: pointerest_start_id
                referencedColumnName: id

    manyToOne:
        pointerestStop:
            targetEntity: Pointerest
            inversedBy: stopover
            joinColumn:
                name: pointerest_stop_id
                referencedColumnName: id

    lifecycleCallbacks: {  }
